# Generated by Django 5.2.8 on 2025-11-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_student_user_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='exam_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Midterm1', 'Midterm2'), ('Midterm2', 'Midterm2'), ('Endterm', 'Endterm'), ('LabInternal', 'LabInternal'), ('Labfinal', 'LabFinal')], max_length=11),
        ),
    ]
