# Generated by Django 5.2.8 on 2025-11-30 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_test_exam_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(default='B.TECH', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='exam_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Midterm1', 'Midterm1'), ('Midterm2', 'Midterm2'), ('Endterm', 'Endterm'), ('LabInternal', 'LabInternal'), ('Labfinal', 'LabFinal')], max_length=11),
        ),
    ]
