# Generated by Django 5.2.8 on 2025-12-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_subject_semester_student_father_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marksheet',
            unique_together={('student', 'semester')},
        ),
        migrations.AddField(
            model_name='marksheet',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='generated_by',
        ),
    ]
